### ISSUE TITLE
Bump to jotai v2

### ISSUE THREAD

**Issue by mcharnet** [Fattafatta/rescript-jotai#8]
Hello @Fattafatta !

Thanks for your bindings. Have you planned to update with jotai v2 ?

**Comment by Fattafatta** [comment]
Hi @mcharnet,

I haven't checked out jotai v2 yet. After a first glance, there are only a few critical changes. The biggest change is the new import option from `jotai/vanilla`.

Since rescript-react also got some updates over the last month I would probably update them too. That would mean only react 18+ would be supported. Would that be a problem?

**Comment by mcharnet** [comment]
Hi @Fattafatta,

Great, thank you very much ! React 18+ is not a problem for us :)

**Comment by Fattafatta** [comment]
Hi @mcharnet,

version 0.3.0 that supports Jotai v2 is now live. There are some breaking changes but it should be relatively easy to adopt it.

Have fun!

**Comment by mcharnet** [comment]
Hi @Fattafatta,

Thank you very much ! I test it during the day :)
